name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do Código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-mock

    - name: Rodar Testes
      run: pytest tests/test_main.py
      
    - name: Simular Deploy Docker
      # Esta etapa apenas demonstra que o processo de build do Docker funciona
      run: |
        echo "Iniciando build da imagem Docker..."
        docker build -t projeto-final-ia-image .
        echo "Build da imagem Docker concluído com sucesso."
        echo "Simulando push para um registry..."
        echo "Simulando deploy no servidor..."